packages:
  - packages/*
  - packages/**/__tests__/**
  - playground/*
  - docs

catalog:
  '@types/node': ^24.13.3
  '@vitejs/plugin-vue': ^5.2.4
  '@vitest/coverage-v8': ^4.1.10
  'playwright': '^1.61.1'
  'tsdown': ^0.22.13
  'typescript': ~5.9.3
  'vite': ^6.4.3
  'vitest': ^4.1.10
  'vue': ^3.5.39
  'vue-tsc': ^3.3.7

onlyBuiltDependencies:
  - esbuild

overrides:
  'vitepress@1>vite': ^6.0.0
patchedDependencies:
  svgo: patches/svgo.patch
