export const VIRTUAL_REGISTER = 'virtual:svg-icons-register'
export const VIRTUAL_NAMES = 'virtual:svg-icons-names'
export const SVG_DOM_ID = '__svg__icons__dom__'
export const XMLNS = 'http://www.w3.org/2000/svg'
export const XMLNS_LINK = 'http://www.w3.org/1999/xlink'
