import { createBaker } from 'svg-icon-baker'
import { normalizePath } from 'vite'
import { warn } from '../utils/logger'
import { buildCompileResult } from './builder'
import { scanIconDirs } from './scanner'
import { loadIconSource, transformIcon } from './transformer'
import type { CompileResult, CompiledIconEntry, CompilerContext, CompilerState, IconCompiler } from '../types'

function normalizeFsPath(filePath: string): string {
  const normalized = normalizePath(filePath)
  return process.platform === 'win32' ? normalized.toLowerCase() : normalized
}

export function createCompiler(ctx: CompilerContext): IconCompiler {
  const baker = createBaker(ctx.options.bakerOptions)
  const iconDirs = ctx.options.iconDirs.map((dir) => {
    const normalized = normalizeFsPath(dir)
    return normalized.endsWith('/') ? normalized : `${normalized}/`
  })

  let inFlight: Promise<CompileResult> | null = null
  const state: CompilerState = {
    dirty: true,
    result: null,
  }

  function reportBakeIssues(icon: CompiledIconEntry): void {
    for (const issue of icon.issues) {
      const targetSuffix = issue.targetId ? ` (targetId: ${issue.targetId})` : ''
      warn(ctx, `Bake issue in "${icon.file}" [${issue.code}]: ${issue.message}${targetSuffix}`)
    }
  }

  function resolveSymbolIdConflicts(icons: CompiledIconEntry[]): CompiledIconEntry[] {
    const seen = new Map<string, CompiledIconEntry>()
    const resolved: CompiledIconEntry[] = []

    for (const icon of icons) {
      const existing = seen.get(icon.id)
      if (!existing) {
        seen.set(icon.id, icon)
        resolved.push(icon)
        continue
      }

      const error = new Error(`Duplicate symbolId "${icon.id}" generated by "${icon.file}". First defined by "${existing.file}".`)
      if (ctx.options.failOnError) {
        throw error
      }
      warn(ctx, `${error.message} Skip duplicate icon.`)
    }

    return resolved
  }

  async function compileIcons(): Promise<CompileResult> {
    const files = await scanIconDirs(ctx.options.iconDirs)
    const compiledIcons = (
      await Promise.all(
        files.map(async (iconFile) => {
          try {
            const source = await loadIconSource(iconFile)
            const cached = ctx.cache.get(iconFile.file, source.hash)
            if (cached) {
              return cached
            }
            const icon = await transformIcon(source, ctx.options, baker)
            ctx.cache.set(icon.file, { hash: icon.hash, icon })
            return icon
          } catch (error) {
            const normalizedError = normalizeBuildError(iconFile.file, error)
            if (ctx.options.failOnError) {
              throw normalizedError
            }
            warn(ctx, `Skip broken icon: ${normalizedError.message}`)
            return null
          }
        })
      )
    ).filter((icon): icon is CompiledIconEntry => icon !== null)

    for (const icon of compiledIcons) {
      reportBakeIssues(icon)
    }
    const icons = resolveSymbolIdConflicts(compiledIcons)
    return buildCompileResult(icons, ctx.options)
  }

  function isIconFile(file: string): boolean {
    const normalized = normalizeFsPath(file)
    if (!normalized.toLowerCase().endsWith('.svg')) {
      return false
    }
    return iconDirs.some((dir) => normalized.startsWith(dir))
  }

  async function getResult(): Promise<CompileResult> {
    if (!state.dirty && state.result) {
      return state.result
    }
    if (inFlight) {
      return await inFlight
    }
    inFlight = compileIcons()
      .then((result) => {
        state.result = result
        state.dirty = false
        return result
      })
      .finally(() => {
        inFlight = null
      })
    return await inFlight
  }

  function invalidate(file?: string): void {
    if (file) {
      ctx.cache.invalidate(file)
    }
    state.dirty = true
  }

  return { getResult, invalidate, isIconFile }
}

function normalizeBuildError(file: string, error: unknown): Error {
  if (error instanceof Error) {
    if (error.message.includes(file)) {
      return error
    }
    return new Error(`Failed on icon ${file}, ${error.message}`, { cause: error })
  }
  return new Error(`Failed on icon ${file}, ${String(error)}`, { cause: error })
}
