name: Create Release Tag

on:
  push:
    tags: ['v*.*.*']

jobs:
  release-tag:
    if: contains(github.event.head_commit.message, 'release')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release for tag
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: ${{contains(github.ref, 'alpha') || contains(github.ref, 'beta')|| contains(github.ref, 'rc')}}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/yangxu52/vite-plugin-svg-icons-ng/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
